version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.filename=/rules-nehora.yaml
      - --log.level=DEBUG
      - --experimental.localPlugins.nehora.moduleName=github.com/Workiz/nehora-test
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./rules-nehora.yaml:/rules-nehora.yaml
      - .:/plugins-local/src/github.com/Workiz/nehora-test/
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      traefik.http.routers.whoami.rule: Host(`whoami.localhost`)
      traefik.http.routers.whoami.middlewares: nehora@file
