name: upload files
on:
  workflow_dispatch:
jobs:
  test:
    name: upload files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-415-workiz-actions-create-action-to-upload-files-to-bucket
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: upload files  
      uses: ./tmp/workiz-actions/upload-files-to-bucket
      with:
        FILES_PATH: './test.txt,./test1.txt'
        BUCKET_PATH: 'gs://slack_notification_test/'
        ALTER_SA_GITHUB_ACTIONS_JSON_KEY: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}