name: upload files
on:
  workflow_dispatch:
jobs:
  test:
    name: upload files
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: upload files  
      uses: ./tmp/workiz-actions/upload-files-to-bucket
      with:
        FILES_PATH: '[./test.txt]'
        BUCKET_PATH: 'gs://test/'
        GKE_SA_HELM_DEPLOYER_KEY: ${{ secrets.GKE_SA_HELM_DEPLOYER_KEY }}