# name: Bump version
# on:
#   push:
#     branches:
#       - workiz.com
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.36.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true
#         PRERELEASE_SUFFIX: 'alpha'
#         INITIAL_VERSION: '1.0.0'

name: Create/update tag
on:
  push:
    branches:
      - workiz.com
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"