name: Create tag
on:
  workflow_dispatch:

jobs:
  create-tag:
    name: create-tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend
      uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: create-tag  
      uses: ./tmp/workiz-actions/create-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}