name: Bump version
on:
  push:
    branches:
      - workiz.com
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.36.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true
#         # PRERELEASE_SUFFIX: 'alpha'
#         # INITIAL_VERSION: '1.0.0'

jobs:
  create-tag:
    name: create-tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-422-workiz-actions-create-action-to-create-new-tag
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: create-tag  
      uses: ./tmp/workiz-actions/create-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true