name: delete branches
on:
  workflow_dispatch:

jobs:
  delete-branches:
    name: delete-branches
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: delete branches  
      run: | 
        git config --global --add safe.directory /github/workspace
        echo "1"
        git fetch --all
        git pull --tags
        echo "2"
        # exists=`git show-ref refs/heads/rc3.331-branch`
        # echo "3"
        #   if [ -n "$exists" ]; then
            echo "rc3.331-branch branch exists!"
            git push origin --delete rc3.331-branch || echo "branch deleted"
            echo "rc3.331-branch backend branch deleted"
            cd ./tmp/nehora
            git config --global --add safe.directory /github/workspace/tmp/frontend
            git push origin --delete rc3.331-branch ||  echo "branch deleted"
            echo "rc3.331-branch frontend branch deleted"
            cd ../..
          # fi 
        echo "here"
        ls
