name: ☁️ deploy production
on:
  workflow_dispatch:

env: 
  BACKEND_BRANCH: ${{ github.ref_name }}

jobs:
  create-tag:
    outputs: 
      BACKEND_BRANCH: ${{ steps.create-rc-branch.outputs.BACKEND_BRANCH }}
    name: create frontend and backend tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Check out workiz-actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: create-tag  
      uses: ./tmp/workiz-actions/create-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}

  dyploy-preprod:
    needs: [create-tag]
    name: dyploy-preprod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  dyploy-prod:
    needs: [create-tag,dyploy-preprod]
    name: dyploy-prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3