name: 🔥 hotfix
on:
  workflow_dispatch:

jobs:
  hot-fix:
    name: hot-fix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-737-hotfix-create-branches-on-hotfix-action
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Init action 
      uses: ./tmp/workiz-actions/init-action
    - name: hot-fix  
      uses: ./tmp/workiz-actions/hot-fix
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
        ANOTHER_REPO: nehora