name: hot fix
on:
  workflow_dispatch:

jobs:
  hot-fix:
    name: hot-fix
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo "$GITHUB_REPOSITORY"
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" \
        https://api.github.com/repos/Workiz/nehora-test/pulls \
        -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":`$GITHUB_REF`,"base":"workiz.com"}'