name: hot fix
on:
  workflow_dispatch:

jobs:
  hot-fix:
    name: hot-fix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: nehora-test
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: hot-fix  
      uses: ./tmp/workiz-actions/hot-fix
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}