name: hot fix
on:
  workflow_dispatch:

jobs:
  hot-fix:
    name: hot-fix
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - run: |-
        echo "open workiz.com pr"
        # curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        # https://api.github.com/repos/Workiz/nehora-test/pulls \
        # -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"'$GITHUB_REF'","base":"workiz.com"}'
        git config --global --add safe.directory /github/workspace
        # git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | while read remote; do git branch --track "${remote#origin/}" "$remote" || echo "hi" ; done
        # git fetch --all
        # git pull --all
        git branch --list 'rc[0-9]*\.[0-9]*-branch' | tail -1
        last_rc_branch=$(git branch --list 'rc[0-9]*\.[0-9]*-branch' | tail -1)
        echo "last_rc_branch $last_rc_branch"
        if [[ "$last_rc_branch" =~ ^rc([0-9]\.[0-9]*)-branch$ ]]; then  
            rc_number=${BASH_REMATCH[1]}
        fi
        if [[ "'$GITHUB_REF'" =~ ^v([0-9]\.[0-9]*)?(-hf[0-9]*)?-branch$ ]]; then  
            branch_number=${BASH_REMATCH[1]}
        fi
        if [[ "rc_number" > "branch_number" ]]; then
          echo "open rc pr"
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/Workiz/nehora-test/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"'$GITHUB_REF'","base":"'$last_rc_branch'"}'
        fi