name: hot fix
on:
  workflow_dispatch:

jobs:
  hot-fix:
    name: hot-fix
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo "open workiz.com pr"
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/Workiz/nehora-test/pulls \
        -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"'$GITHUB_REF'","base":"workiz.com"}'
        git config --global --add safe.directory /github/workspace
        last_rc_branch=$(git branch --list 'rc[0-9]*\.[0-9]*-branch' | tail -1)
        echo "$last_rc_branch"
        if [[ "$last_rc_branch" =~ ^rc([0-9]\.[0-9]*)-branch$ ]]; then  
            rc_number=${BASH_REMATCH[1]}
        fi
        if [[ "'$GITHUB_REF'" =~ ^v([0-9]\.[0-9]*)?(-hf[0-9]*)?-branch$ ]]; then  
            branch_number=${BASH_REMATCH[1]}
        fi
        if [[ "rc_number" > "branch_number" ]]; then
          echo "open rc pr"
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/Workiz/nehora-test/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"'$GITHUB_REF'","base":"'$last_rc_branch'"}'
        fi