# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER, IMAGE, REGISTRY_HOSTNAME and DEPLOYMENT_NAME environment variables (below).

name: New full release to production with frontend.

on:
  workflow_dispatch:

env:
  BUCKET_PATH:  static-cdn.workiz.com/fe/pre/latest
  BUCKET_ROLLBACK_PATH:  static-cdn.workiz.com/fe/older
  GITHUB_SHA: ${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}
  GKE_CORE_PROJECT: ${{ secrets.GKE_PROJECT_CORE }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
  AMPLITUDE_SECRET_KEY: ${{ secrets.AMPLITUDE_SECRET_KEY }}
  GCP_REGION: us-central1
  GCP_ZONE: us-central1-b
  MAILGUNKEY: ${{ github.MAILGUNKEY}}
  TEMPLATE: backend-
  MIG:  preprod-ig
  URL_MAP_NAME: backend-preprod-lb
  BUCKET_PRE_PATH:  static-cdn.workiz.com/fe/pre/latest
  API_PATH_MATCHER: path-matcher-7
  APP_PATH_MATCHER: path-matcher-3
  PREPROD_PATH_MATCHER: path-matcher-6
  FIRST_GROUP: preprod-ig
  SECOND_GROUP: preprod2-ig
  MAX_RPS: 100
  WORKIZ_INTERNAL_BE: workiz-interal-all-https
  LONG_PROCESS_BE: long-proccess-api
  AUTOSCALE_CPU: 0.35
  COOL_DOWN_SECS: 120
  MAX_REPLICAS: 20
  MIN_REPLICAS: 1
  PROD_DEFAULT_MIN_REPLICAS: 3
  PROD_BE_BUCKET: be-assets-1
  PREPROD_BE_BUCKET: be-assets-2

jobs:

  check-github-actor:
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: check github actor 
      uses: ./tmp/workiz-actions/check-github-actor
      with:
        GITHUB_ACTOR: ${{ github.actor }}

  create-release-branch:
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    needs: [check-github-actor]
    name: create frontend and backend branches 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout frontend
      uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/frontend
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/workiz-actions
    - name: create branches 
      uses: ./tmp/workiz-actions/create-rc-branch
      with:
        GITHUB_ACTOR: ${{ github.actor }}
    - name: set branch output
      id: branch
      run: |
        echo  ${{ env.BRANCH }}
        echo "::set-output name=branch::${{ env.BRANCH }}"

  build-fe-preprod:
    needs: [create-release-branch]
    name: build bundle.js & push to fe/pre/latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend
      uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: install correct node version
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: use env.js for ci
      run: mv env-ci.js env.js
    - name: install npm modules with npm ci
      run: npm ci
    # - name: unit test
    #   if: success()
    #   run: |
    #     npm run test 
    - name: build asset
      if: success()
      run: |
        npm run build-ci
    # Rollout to Ig
    # - name: deploy
    #   if: success()
    #   run: |
    #     gsutil -m cp -z js /var/tmp/bundle.js* gs://$BUCKET_PATH/    
    #     curl https://us-central1-genial-runway-125805.cloudfunctions.net/build-version?env=preprod.workiz.com

  db-migrate:
    needs: [create-release-branch]
    name: db migrate RC MySQL
    # runs-on: backend-runner
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.create-release-branch.outputs.branch}}
      # - uses: actions/checkout@v3
      # - name: Checkout shared actions
      #   uses: actions/checkout@v3
      #   with:
      #     repository: Workiz/workiz-actions
      #     ref: workiz.com
      #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
      #     path: ./tmp/workiz-actions
      # - name: Checkout shared actions
      #   uses: actions/checkout@v3
      #   with:
      #     repository: Workiz/workiz-actions
      #     ref: workiz.com
      #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
      #     path: ./tmp/workiz-actions
      # - name: Run flyway migrate
      #   uses: ./tmp/workiz-actions/flyway
      #   with:
      #     url: "jdbc:mysql://${{ env.MYSQL_HOST }}:3306/sendajobprod"
      #     user: ${{ env.MYSQL_USER }}
      #     password: ${{ env.MYSQL_PW }}
      #     locations: filesystem:./conf/db_migrations/sql
      #     command: migrate
      # - name: Send failure slack msg 
      #   if: failure()  
      #   uses: ./tmp/workiz-actions/slack-msg
      #   with:
      #     CHANNEL: 'release-committee'
      #     MESSAGE: 'db migrate on rc database failed :sob:'
      #     SUCCESS: false
      #     WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
      #     LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]' 

  create-rc:
    needs: [create-release-branch]
    name: create RC from branch.
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.create-release-branch.outputs.branch}}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}
    - name: Create new environment
      if: success()
      run: | 
        # gcloud compute ssh root@sajdev-rc  --zone=${GCP_ZONE} --command "sudo bash /var/infra/scripts/backend-rc/recreate_rc.sh '${{needs.create-release-branch.outputs.branch}}'" --project=$GKE_CORE_PROJECT
    # - name: Send failure slack msg 
    #   if: failure()  
    #   uses: ./tmp/workiz-actions/slack-msg
    #   with:
    #     CHANNEL: 'release-committee'
    #     MESSAGE: 'RC failed to update :sob:'
    #     SUCCESS: false
    #     WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
    #     LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]'   
  update-qa:
    needs: [create-release-branch]
    name: update qa.workiz.com
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{needs.create-release-branch.outputs.branch}}
    # - name: Checkout
    #   uses: actions/checkout@v3
    # - name: Checkout shared actions
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Workiz/workiz-actions
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    #     path: ./tmp/workiz-actions
    # - uses: google-github-actions/auth@v0
    #   with:
    #     credentials_json: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}
    # - name: Create new environment
    #   if: success()
    #   run: | 
    #     gcloud compute ssh root@sajdev --zone=${GCP_ZONE} --command "sudo bash /var/infra/scripts/backend-rc/qa-tag-pull.sh '${{needs.create-release-branch.outputs.branch}}'" --project=$GKE_CORE_PROJECT
    # - name: Send failure slack msg 
    #   if: failure()  
    #   uses: ./tmp/workiz-actions/slack-msg
    #   with:
    #     CHANNEL: 'release-committee'
    #     MESSAGE: 'qa.workiz.com failed to update :sob:'
    #     SUCCESS: false
    #     WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
    #     LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]'


