# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Assets on new tag

on:
  push:
    tags:
    - '*'
# Environment variables available to all jobs and steps in this workflow
env:
  BUCKET_PATH:  static-cdn.workiz.com/fe/rc/latest
  BUCKET_ROLLBACK_PATH:  static-cdn.workiz.com/fe/older
  GITHUB_SHA: ${{ github.sha }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}
jobs:
  build-fe-preprod:
    name: build bundle.js & push to fe/pre/latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: install correct node version
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: use env.js for ci
      run: mv env-ci.js env.js
    - name: install npm modules with npm ci
      run: npm ci
    - name: unit test
      if: success()
      run: |
        npm run test 
    - name: build asset
      if: success()
      run: |
        npm run build-ci
    # Rollout to Ig
    - name: deploy
      if: success()
      run: |
        gsutil -m cp -z js /var/tmp/bundle.js* gs://$BUCKET_PATH/    
        curl https://us-central1-genial-runway-125805.cloudfunctions.net/build-version?env=preprod.workiz.com