name: PR Lint New
on:
  pull_request:
    types: [opened, edited, reopened]

env:
  STATUS_CODE: 200

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: check pr titel
      run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}"  \
          -X GET \
          -H "Authorization: Basic bmVob3JhLm1vc2hlQHdvcmtpei5jb206cGNCS0dCSXhhMG1SbjRmN2FRTWtCMUM5" \
          -H "Content-Type: application/json" \
          "https://workiz.atlassian.net/rest/api/2/issue/${{ github.event.pull_request.title }}")
          echo "STATUS_CODE=$STATUS_CODE" >> $GITHUB_ENV
    - uses: mshick/add-pr-comment@v1
      if: ${{ env.STATUS_CODE==404 }}
      env:
        GITHUB_TOKEN: ${{github.token}}
      with:
        message: |
          :x: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Jira ticket ID was not found at PR title** &nbsp;&nbsp;&nbsp; :suspect:
        allow-repeats: true
    - uses: mshick/add-pr-comment@v1
      if: ${{ env.STATUS_CODE==200 }}
      env:
        GITHUB_TOKEN: ${{github.token}}
      with:
        message: |
          "Great job!"
        allow-repeats: true
    - name: exit_code
      run: exit ${{ env.STATUS_CODE}}-200