name: PR Lint
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    name: check pr
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-440-pr-lint-remove-quotes
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: pr lint  
      uses: ./tmp/workiz-actions/pr-lint
      with:
        JIRA_TOKEN: ${{secrets.JIRA_TOKEN}}