name: PR Lint
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    name: check pr
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: pr lint  
      uses: ./tmp/workiz-actions/pr-lint
      with:
        JIRA_TOKEN: ${{secrets.JIRA_TOKEN}}

        