name: progress bar
on:
  workflow_dispatch:
    
    

jobs:

  progress-bar:
    runs-on: ubuntu-latest
    steps: 
    - name: infra-api failed
      run: | 
        fgecho "failure"
    - name: infra-api failed
      if: ${{ failure() && startsWith(github.ref_name, 'wo') }}
      run: | 
        echo "failure"
    - name: infra-api failed
      if: ${{ startsWith(github.ref_name, 'wo') }}
      run: | 
        echo "not failure"