name: slack msg
on:
  workflow_dispatch:
    
jobs: 
  send-slack-msg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: test
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/workiz-actions
    - name: Send failure slack msg 
      uses: ./tmp/workiz-actions/slack-msg
      with:
        CHANNEL: 'nehora'
        MESSAGE: 'Native automation failed to finish :sob:'
        SUCCESS: false
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
        LINKS: '[{"name" :" Allure Report","link": "https://storage.googleapis.com/workiz-qa-reports/allure-report/index.html"},
                      {"name": " Link to GitHub Action" , "link" : "https://github.com/Workiz/native-automation/actions/runs"}]' 
    - name: Send failure slack msg 
      uses: ./tmp/workiz-actions/slack-msg
      with:
        CHANNEL: 'nehora'
        MESSAGE: 'Native automation failed to finish :sob:'
        SUCCESS: false
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
