name: TEST
on:
  workflow_dispatch:
    
    

jobs:

  progress-bar:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out workiz-actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-766-cicd-check-if-there-is-a-way-to-stop-a-github-workflow-if-already-running
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: init
      uses: ./tmp/workiz-actions/init-action
      env:
        CHECK_DOUBLE_RUN: true
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
    - name: sleep
      run: sleep 20
      shell: bash
    