name: test
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'

jobs:

  check-github-actor:
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo "${{ github.event }}"
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: check github actor 
      uses: ./tmp/workiz-actions/check-github-actor
      with:
        GITHUB_ACTOR: ${{ github.actor }}
    - name: infra-api failed
      if: failure()  
      run: | 
        curl --location --request POST 'https://infra-api.workiz.com/releaseProgress/update_job_status/' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "job_name" : "rc_deploy",
            "status" : "failed"
            }' || echo -e "\e[1;31m infra-api sent failed"

  
   
