name: test
on:
  workflow_dispatch:
    

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |-
        status=$(curl --location --request GET 'https://infra-api.workiz.com/releaseProgress/get_train_status/' \
        --header 'WORKIZ_INFRA_AUTH: ${{ secrets.GH_TOKEN_REPOS }}' | jq .'status')
        echo "$status"
        if ! $status ; then
            echo "Error - train is lock now"
            exit 1
        fi
  job2: 
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo "test"

  
   