name: test vfdkl
on:
  workflow_dispatch:
    
   
 
jobs:

  
  init:
    name: init
    runs-on: ubuntu-latest
    steps:
    - name: set branch output
      id: branch
      run: |
        echo "$GITHUB_WORKFLOW"