name: TEST1
on:
  workflow_dispatch:
    

jobs:

  run-api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared actions
        uses: actions/slack-msg@workiz.com
        with:
          CHANNEL: 'nehoramoshe'
          MESSAGE: ':octagonal_sign: Train didnt run, since it was locked.:lock:'
          SUCCESS: false
          WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}