name: TEST1
on:
  workflow_dispatch:
    

jobs:

  run-api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          repository: Workiz/workiz-actions
          ref: DEVOPS-939-axiom-total-lockdown
          token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
          path: ./tmp/workiz-actions
      - name: init
        uses: ./tmp/workiz-actions/init-action