name: TEST
on:
  workflow_dispatch:
    

jobs:

  run-api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_HELM_DEPLOYER_KEY }}