name: TEST
on:
  workflow_dispatch:

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir test1; cd test1; touch test.txt
    - run: mkdir test2; cd test2; touch test2.txt
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with: 
          name: test
          path: test1
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with: 
          name: test_
          path: test2
  test1:
    runs-on: ubuntu-latest
    name: Prepare to clone a new version
    needs: [test]
    steps:
    - uses: actions/download-artifact@v3
    - run: ls
 