name: test
on:
 workflow_dispatch:
   
  inputs:
      environment:
        description: 'Define env name'     
        required: false
        default: 'prod'
 
jobs:

  
  init:
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      rc_tag: ${{ steps.branch.outputs.rc_tag }}
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: set branch output
      id: branch
      run: |
        echo "::set-output name=branch::jgkfld"
        echo "::set-output name=rc_tag::vjospl"
  job2: 
    needs: [Init]
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: set branch output
      id: branch
      run: |
        echo "${{ needs.create-rc-branches-and-tags.outputs.rc_tag }}"    