name: test
on:
  workflow_dispatch:
    

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |-
        status=$(curl --location --request POST 'https://infra-api.workiz.com/releaseProgress/get_train_status/')
        if [[ "$status" == "false" ]]; then
            echo "Error - train is lock now"
            exit 1
        fi
  job2: 
    runs-on: ubuntu-latest
    steps:
    - run: |-
        echo "test"

  
   