name: send slack msg on update rc branch
on:
 push:
  branches:    
    - 'rc*'
  paths:
    - '*'
jobs:
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: check if first commit
      run: |-
          echo "GITHUB_REF_NAME $GITHUB_REF_NAME"
          git config --global --add safe.directory /github/workspace
          git pull
          git checkout workiz.com
          git pull
          git checkout $GITHUB_REF_NAME
          
          diff=$(git cherry -v workiz.com)
          echo "diff $diff"
          if [[ "$diff" == "" ]]; then 
            echo "This is the first commit of branch"
            exit 1
          fi