name: test

on:
  workflow_dispatch:

jobs:
  releases-msg:
    name: releases-msg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: v3.397-hf1-branch
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-589-github-actions-create-releases-msg
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    # - name: Checkout frontend
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Workiz/frontend
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    #     path: ./tmp/frontend
    - name: releases-msg
      uses: ./tmp/workiz-actions/releases-msg
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}