name: TEST
on:
  workflow_dispatch:
    
   
jobs:
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: | 
        curl --location --request POST 'https://infra-api-staging.workiz.com/github/new_release_pr/' \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "github_token" : "${{ secrets.GH_TOKEN_REPOS }}"
        }'
