name: ☁️ deploy production K8S
on:
  workflow_dispatch:
    inputs:
      run-automation:
        type: boolean
        description: run-automation
        default: true
  schedule:
    - cron: '0 9 * * 0-4'

env: 
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wstgcluster


jobs:
  
  build-fe-prod:
    if: ${{ github.event.inputs.run-automation == 'true' }}
    name: build bundle.js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./

  build-fe-prod-experimental:
    name: build bundle.js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Workiz/frontend
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./