name: send slack msg on update rc branch
on:
 push:
  branches:    
    - 'rc*'

 
jobs:

  
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: check if first commit
      run: |-
          git config --global --add safe.directory /github/workspace
          diff=$(git cherry -v origin/workiz.com)
          if [[ "$diff" == "" ]]; then 
            echo "first commit of branch"
            exit 1
          fi
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: Send msg to 'release-committee' 
      uses: ./tmp/workiz-actions/slack-msg
      with:
        CHANNEL: 'nehora'
        MESSAGE: ' @${{ github.actor }} just push commit to $GITHUB_REF_NAME branch.'
        SUCCESS: true
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
        LINKS: '[{"name" :"commit","link": "https://github.com/Workiz/nehora-test/commit/$GITHUB_SHA"}]'


