name: ☁️ deploy production K8S
on:
  workflow_dispatch:
    inputs:
      run-automation:
        type: boolean
        description: run-automation
        default: true

env: 
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wstgcluster


jobs:
  build-frontend-bundle-rc:
    name: build bundle.js & push to workiz-frontend-assets-rc bucket
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.ALTER_SA_GITHUB_ACTIONS_JSON_KEY }}
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
  # run-cypress-tests:
  #   name: run cypress tests
  #   uses: Workiz/workiz-cypress-automation/.github/workflows/run-cypress-parallel.yml@DEVOPS-1025-cypress-branch-checkout
  #   secrets: inherit
  #   with: 
  #     tag: rc111
