name: test
on:
 workflow_dispatch:
   

 
jobs:

  
  init:
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: check github actor 
      uses: ./tmp/workiz-actions/init-action