name: TEST
on:
  workflow_dispatch:

env: 
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}  
  ASSETS_RC_PATH_URL: "https://assets-rc.workiz.com" 
  FRONTEND_ASSETS_RC_BUCKET_PATH: nehoratest

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          repository: Workiz/backend
          ref: workiz.com
          token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/workiz-actions
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_HELM_DEPLOYER_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0' 
    - run: |
        gcloud components install beta
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Build and push backend assets
      run: |-
        npm ci
        ASSETS_PATH="$ASSETS_RC_PATH_URL/$GITHUB_SHA/" npm run build
        gsutil -m cp -z js,css,html,json,ico,eot,otf,ttf,gif,jpeg,jpg,png,tiff  -a public-read  -r _assets/*   gs://$FRONTEND_ASSETS_RC_BUCKET_PATH/$GITHUB_SHA/with_z/_assets
    - name: Build and push backend assets
      run: |-
        npm ci
        ASSETS_PATH="$ASSETS_RC_PATH_URL/$GITHUB_SHA/" npm run build
        gsutil -m cp  -a public-read  -r _assets/*   gs://$FRONTEND_ASSETS_RC_BUCKET_PATH/$GITHUB_SHA/_assets
    # - name: push to workiz-frontend-assets-rc bucket
    #   uses: 'google-github-actions/upload-cloud-storage@v1'
    #   with:
    #     path: '_assets'
    #     destination: '${{env.FRONTEND_ASSETS_RC_BUCKET_PATH}}/${{github.sha}}/_assets'
        # glob: 'bundle.js*'
        # parent: false