name: ☁️ deploy production K8S
on:
  workflow_dispatch:
    inputs:
      run-automation:
        type: boolean
        description: run-automation
        default: true
  schedule:
    - cron: '*/15 * * * *'

env: 
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wstgcluster


jobs:
  
  run-cypress-tests:
    name: run cypress tests
    uses: Workiz/workiz-cypress-automation/.github/workflows/run-cypress-parallel.yml@workiz.com
    secrets: inherit
    with: 
      tag: rc111
