name: test
on:
  workflow_dispatch:
    
  # schedule:
  #   - cron:  '*/5 * * * *'

jobs:

  create-rc-branches-and-tags:
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    name: create frontend and backend branches and tags
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: test
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/workiz-actions
    - name: create branches 
      uses: ./tmp/workiz-actions/create-rc-branches-and-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}
        ANOTHER_REPO: nehora
    - name: set branch output
      id: branch
      run: |
        echo "::set-output name=branch::${{ env.BRANCH }}"
        

  
   
