name: send slack msg on update rc branch
on:
 push:
  branches:    
    - 'rc*'

 
jobs:
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      run: echo "${{ github.actor }}"

      
