name: test
on:
  workflow_dispatch:
    

jobs:

  send-slack-msg:
    name: send slack msg
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: ${{ github.ref_name }}
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./   
    - run: |
        git rev-parse --abbrev-ref HEAD
        ls
   