name: TEST1
on:
  workflow_dispatch:
    

env: 
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: wstgcluster
  GKE_ZONE: us-central1-b
  GITHUB_SHA: ${{ github.sha }}
  ALTER_IMAGE: backend-php
  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
  AMPLITUDE_SECRET_KEY: ${{ secrets.AMPLITUDE_SECRET_KEY }}
  BUCKET_PATH:  static-cdn.workiz.com/fe
  ASSETS_PATH_URL: "https://assets.workiz.com"
  ASSETS_BUCKET_PATH: assets.workiz.com
  K8S_NAMESPACE: prod
  RELEASE_NAME: backend-php-app-new
  BACKEND_PHP_HELM_VERSION: "0.1.0"
  NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  FRONTEND_ASSETS_BUCKET_PATH: workiz-fe-assets-dev/staging-dev
  ASSETS_PATH_URL_STAGING: "https://assets-dev-be.workiz.com/staging-dev"

jobs:

  build-fe-staging-dev:
    name: build bundle.js for staging-dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out workiz-actions
      uses: actions/checkout@v4
      with:
        repository: Workiz/workiz-actions
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: slack msg about what going to releas
      id: slack-msg-about-what-going-to-release
      run: |
        json=$(curl --location --request POST 'https://infra-api.workiz.com/github/get_new_release_pr/' \
        --header 'Content-Type: application/json' \
        --header 'WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}')


        # Utility function to parse PRs
        parse_prs() {
          local prs="$1"
          echo "$prs" | jq -r '.[] | "* [\(.message)](\(.url)) by \(.github_actor)"'
        }

        # Extract frontend and backend PRs
        frontend_prs=$(echo $json | jq '.frontend.prs')
        backend_prs=$(echo $json | jq '.backend.prs')

        # Extract tag values
        new_tag=$(echo $json | jq -r '.frontend.new_tag')
        last_tag=$(echo $json | jq -r '.frontend.last_tag')

        # Generate message
        msg="## Release Notes for ${new_tag}

        ### Frontend Changes (from ${last_tag} to ${new_tag}):
        $(parse_prs "$frontend_prs")

        ### Backend Changes (from ${last_tag} to ${new_tag}):
        $(parse_prs "$backend_prs")
        "
        # Output the message
        echo $msg
        curl --location --request POST 'https://infra-api.workiz.com/slack/send_slack_msg/' \
            --header 'WORKIZ_INFRA_AUTH: TotF2Yr6r1ju9ZHp' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "msg" : "$msg",                                                                                                
                "success" : true,
                "channel" : "nehoramoshe"           
        }'