name: AAA
on:
  workflow_dispatch:
  push:

jobs:
  create-commit:
    name: push commit to nehora
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: ${{ github.ref_name }}
        token: ${{github.token}}
        path: nehora
        set-safe-directory: nehora
    - name: create empty commit
      id: empty-commit
      run: |
        cd nehora
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit --allow-empty -m "Empty commit from frontend with commit ${{ github.sha }}"
        git push
