name: test
on:
  workflow_dispatch:
    

jobs:

  send-slack-msg:
    name: send slack msg
    runs-on: ubuntu-latest
    steps: 
    # - name: Checkout backend
    #   uses: actions/checkout@v3 
    #   with:
    #     repository: Workiz/backend
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_REPOS }}
    #     path: ./
    # - name: Checkout frontend
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Workiz/frontend
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_REPOS }}
    #     path: ./tmp/frontend
    # - name: Checkout shared actions
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Workiz/workiz-actions
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    #     path: ./tmp/workiz-actions
    # - name: get last tag
    #   run: |
    #     git config --global --add safe.directory /github/workspace
    #     git fetch --all
    #     git pull --tags
    #     LAST_TAG=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -1) 
    #     if [[ "$LAST_TAG" =~ ^v([0-9]\.[0-9]*)$ ]]; then
    #       echo "${BASH_REMATCH[1]}"
    #       git checkout workiz.com
    #       # git push origin --delete rc${BASH_REMATCH[1]}-branch
    #     fi
    #     current_branch=$(git rev-parse --abbrev-ref HEAD)
    #     echo "current branch $current_branch"
    #     if [[ "$current_branch" =~ ^rc.* ]]; then
    #       echo "rc branch"
    #       LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -2) 
    #     else
    #       LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*" | tail -2) 
    #     fi
    #     echo "last tags $LAST_TAGS"
    #     if [[ "$LAST_TAGS" =~ ^(v[a-z0-9\.\-]*).*(v[a-z0-9\.\-]*)$ ]]; then
    #       echo "backend last tag ${BASH_REMATCH[2]}"
    #       echo "backend prev tag ${BASH_REMATCH[1]}"
    #       LAST_TAG=${BASH_REMATCH[2]}
    #       PREV_TAG=${BASH_REMATCH[1]}
    #     fi
    #     NOTE=$(curl  -X POST  -H "Accept: application/vnd.github+json"   -H "Authorization: token ${{ secrets.GH_TOKEN_REPOS }}"   https://api.github.com/repos/Workiz/backend/releases/generate-notes -d '{"tag_name":"'$LAST_TAG'","previous_tag_name":"'$PREV_TAG'"}' |  jq .body)
    #     NOTE="${NOTE%\"}"
    #     NOTE="${NOTE#\"}"
    #     NOTE=${NOTE//\'/}
    #     NOTE=${NOTE//\*/•}
    #     cd ./tmp/frontend
    #     git config --global --add safe.directory /github/workspace/tmp/frontend
    #     git fetch --all
    #     git pull --tags
    #     LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -1) 
    #     if [[ "$LAST_TAGS" =~ ^v([0-9]\.[0-9]*)$ ]]; then
    #       echo "${BASH_REMATCH[1]}"
    #       git checkout workiz.com
    #       # git push origin --delete rc${BASH_REMATCH[1]}-branch
    #     fi
    #     LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -2)
    #     if [[ "$LAST_TAGS" =~ ^(v[a-z0-9\.\-]*).*(v[a-z0-9\.\-]*)$ ]]; then
    #       echo "frontend last tag ${BASH_REMATCH[2]}"
    #       echo "frontend prev tag ${BASH_REMATCH[1]}"
    #       LAST_TAG=${BASH_REMATCH[2]}
    #       PREV_TAG=${BASH_REMATCH[1]}
    #     fi
    #     NOTE2=$(curl  -X POST  -H "Accept: application/vnd.github+json"   -H "Authorization: token ${{ secrets.GH_TOKEN_REPOS }}"   https://api.github.com/repos/Workiz/frontend/releases/generate-notes -d '{"tag_name":"'$LAST_TAG'","previous_tag_name":"'$PREV_TAG'"}' |  jq .body)
    #     NOTE2="${NOTE2%\"}"
    #     NOTE2="${NOTE2#\"}"
    #     NOTE2=${NOTE2//\'/}
    #     NOTE2=${NOTE2//\*/•}
    #     echo "*backend* NOTE2 *frontend* $NOTE2"
    #     NOTE=":php: *backend* \n$NOTE \n\n:react: *frontend* \n$NOTE2 "
    #     # NOTE=${NOTE//\*/•}
    #     echo "NOTE=$NOTE" >> $GITHUB_ENV
    #     echo "env NOTE ${{env.NOTE}}"
    #     echo "NOTE $NOTE"
    # - name: Send pr list to releases 
    #   uses: ./tmp/workiz-actions/slack-msg
    #   with:
    #     CHANNEL: 'releases'
    #     MESSAGE: '*we are realesed a new version to production* \n*Developers that got mentioned, please check your changes and thumbs-up on this message, so we know that you have checked your code change* :thumbsup: \n ${{env.NOTE}}'
    #     SUCCESS: true
    #     WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
    #     LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]'
    - name: Send msg to rnd 
      uses: ./tmp/workiz-actions/slack-msg
      with:
        CHANNEL: 'nehora'
        MESSAGE: 'Hi all \nrelease is out :slightly_smiling_face: \n you can see \#releases notes in releases channel'
        SUCCESS: true
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
        LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]'
