name: test
on:
 workflow_dispatch:
   
  inputs:
      environment:
        description: 'Define env name'     
        required: false
        default: 'prod'
 
jobs:

  init:
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Check out workiz-actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-493-deploy-prod-check-commit-before-create-new-tag
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: create-tag  
      uses: ./tmp/workiz-actions/create-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}
        ANOTHER_REPO: nehora