name: TEST
on:
  push:
    
   
jobs: 
  send-slack-msg:
    name: send slack msg
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-944-train-run-cypress-as-part-of-train
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: e2e-tests
      id: e2e-tests
      uses: ./tmp/workiz-actions/e2e-tests
      with:
        TAG: "v3.333"
        BRANCH: "v3.333-branch"
        GKE_SA_HELM_DEPLOYER_KEY: ${{ secrets.GKE_SA_HELM_DEPLOYER_KEY }}