name: send slack msg on update rc branch
on:
 push:
  branches:    
    - 'rc*'

 
jobs:
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:

    
    - run: echo "${{ github.actor }}"
    # - name: Checkout shared actions
    #   uses: actions/checkout@v3
    #   with:
    #     repository: Workiz/workiz-actions
    #     ref: workiz.com
    #     token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
    #     path: ./tmp/workiz-actions
    # - name: Send msg to 'release-committee' 
    #   uses: ./tmp/workiz-actions/slack-msg
    #   with:
    #     CHANNEL: 'nehora'
    #     MESSAGE: 'Hi all \n hotfix is out :fire: \n you can see releases notes in #releases channel'
    #     SUCCESS: true
    #     WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}


