name: TEST
on:
  workflow_dispatch:
    
    

jobs:

  progress-bar:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Check out workiz-actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-757-deploy-prod-fix-hotfix-pr
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
        fetch-depth: '0'
    - name: hotfix-pr
      uses: ./tmp/workiz-actions/hotfix-pr
      with: 
        CREATE_RC_TAGS: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_REPOS }}
        ANOTHER_REPO: nehora
        WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
    