name: TEST
on:
  workflow_dispatch:
    

jobs:

  run-api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared actions
        uses: actions/checkout@v3
        with:
          repository: Workiz/workiz-actions
          ref: DEVOPS-766-cicd-check-if-there-is-a-way-to-stop-a-github-workflow-if-already-running
          token: ${{ secrets.GH_TOKEN_REPOS }}
          path: ./tmp/workiz-actions
      - name: Send slack msg 
        uses: ./tmp/workiz-actions/init-action
        env:
          CHECK_DOUBLE_RUN: true
          WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
      - run: sleep 20