name: TEST
on:
  workflow_dispatch:

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir test1; cd test1; touch test.txt
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with: 
          name: test1
          path: test1
  test1:
    runs-on: ubuntu-latest
    name: Prepare to clone a new version
    needs: [test]
    steps:
    - run: ls
 