name: TEST1
on:
  workflow_dispatch:
  repository_dispatch:
    types: [train]
    

jobs:

  run-api-tests:
    name: Run api tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shared actions
        run: echo ${{ github.event.client_payload.tag }}