name: TEST
on:
 push:
   
jobs:
  send-slack-msg:
    name: send slack msg on update rc branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: | 
        curl -X POST -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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" \
        https://api.github.com/repos/Workiz/nehora-test/dispatches \
        -d '{"event_type":"train","tag":"rc3.111"}'
