name: 🚅 train

on:
  workflow_dispatch:
    

env:
  BUCKET_PATH:  static-cdn.workiz.com/fe/rc/latest
  NPM_READONLY_TOKEN: ${{secrets.NPM_READONLY_TOKEN}}
  GKE_CORE_PROJECT: ${{ secrets.GKE_PROJECT_CORE }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GCP_ZONE: us-central1-b
  MIG:  preprod-ig
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:

  check-github-actor:
    name: check github actor
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shared actions
      uses: actions/checkout@v3
    - name: Checkout nehora
      uses: actions/checkout@v3
      with:
        repository: Workiz/nehora
        ref: workiz.com
        token: ${{ secrets.GH_TOKEN_REPOS }}
        path: ./tmp/nehora
    - name: Checkout shared actions
      uses: actions/checkout@v3
      with:
        repository: Workiz/workiz-actions
        ref: DEVOPS-567-workiz-actions-refactor-tag-creation
        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
        path: ./tmp/workiz-actions
    - name: test
      run: | 
        curl -s -X POST https://api.github.com/repos/Workiz/nehora-test/git/refs \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d @- << EOF
        {
        "ref": "refs/tags/test-tag",
        "sha": "cc93d549e0917181b61c54fedfa29c93dd98d8c8"
        }
        EOF
    - name: check github actor 
      uses: ./tmp/workiz-actions/create-tags-and-branches
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ANOTHER_REPO: nehora

